language: android
jdk:
  - oraclejdk8
android:
  components:

# Defaults  
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    
## Emulator
    - sys-img-armeabi-v7a-android-26

# Setup JAVA env for components
before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  
# Start emulator
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
# Notifications
notifications:
  email:
    recipients:
      - brandonschabell@gmail.com
    on_success: [change]
    on_failure: [always]
